use jobFinder;
delete from JOB_SEEKER;
ALTER TABLE JOB_SEEKER AUTO_INCREMENT = 0;
insert into JOB_SEEKER values (1, "barnettchristine@jones.com", "mg8hqSeW", "Provident provident modi qui fuga magnam. Molestias occaecati dolorem unde rem vitae nulla. Ut labore labore animi eaque doloremque. Neque rem libero laudantium sit molestias nemo perferendis.", CURDATE(), CURDATE(), "2016-06-11", "65729152306", "female", "Jamie", "Britton", "Brown", "833 Jennifer Hollow Suite 578", "West Kaitlinburgh", "Brunei Darussalam");
insert into JOB_SEEKER_SKILL values (1,"Dietitian");
insert into JOB_SEEKER_SKILL values (1,"Curator");
insert into JOB_SEEKER_SKILL values (1,"Optician");
insert into JOB_SEEKER_SKILL values (1,"Designer");
insert into JOB_SEEKER_SKILL values (1,"Occupational hygienist");
insert into JOB_SEEKER_SKILL values (1,"Public relations officer");
insert into EDUCATION values (NULL,"Laborum qui repellat doloribus cumque vero. Et blanditiis quaerat voluptas officiis. A neque nam libero eligendi. Architecto minima et sint earum vero ullam tempore magni.","Thibault Institution","2016-03-16","2016-09-08","High School",1);
insert into EDUCATION values (NULL,"Fugiat quos velit tenetur illum blanditiis harum facilis eum. Deserunt nihil saepe quo. Porro ad doloremque inventore dolores labore quo.","Montford School","2016-08-19","2016-06-01","Associate's Degree",1);
insert into EDUCATION values (NULL,"Eos sed magnam sunt illo ex error. Nesciunt beatae iste voluptate amet. Quidem sequi quam accusamus facilis molestias quidem a.","Busse Institution","2016-11-13","2016-07-09","Doctorate",1);
insert into EDUCATION values (NULL,"Nisi voluptas fugiat nemo delectus. Aperiam sint eos maxime odit suscipit repudiandae. Accusamus saepe quidem eius. Vel perferendis libero nam est maxime.","Arnold School","2016-01-28","2016-05-13","Bachelor's Degree",1);
insert into WORK_EXPERIENCE values (NULL,"Acupuncturist","2016-01-20","2016-07-10","Dawson, Rogers and Parks","Dicta debitis occaecati repudiandae sint blanditiis quae. Veniam esse possimus rem quisquam suscipit. Recusandae magnam deleniti dolore sed harum perspiciatis.",1);
insert into WORK_EXPERIENCE values (NULL,"Customer service manager","2016-03-09","2016-09-10","Stout-Ferguson","Ipsum quisquam accusamus similique animi asperiores ex. Debitis delectus dicta inventore hic voluptate corrupti ratione. Amet laudantium iure quam magnam recusandae velit sapiente.",1);
insert into JOB_SEEKER values (2, "coopersara@yahoo.com", "mjEyJTntF7", "Ex consequatur alias aliquid dolore distinctio aut saepe illo. Accusantium voluptas minus laboriosam quo. Fugit culpa consequuntur molestias.", CURDATE(), CURDATE(), "2016-05-31", "61566411533", "female", "Cynthia", "Midkiff", "Garvin", "793 Martinez Skyway", "Lake Laurenstad", "Haiti");
insert into JOB_SEEKER_SKILL values (2,"Field trials officer");
insert into JOB_SEEKER_SKILL values (2,"Facilities manager");
insert into JOB_SEEKER_SKILL values (2,"Fashion designer");
insert into JOB_SEEKER_SKILL values (2,"Risk analyst");
insert into JOB_SEEKER_SKILL values (2,"Software engineer");
insert into JOB_SEEKER_SKILL values (2,"Education administrator");
insert into EDUCATION values (NULL,"Quae laudantium laudantium nisi dolore. Nihil odio porro autem.","Sweeney School","2016-11-15","2016-09-17","Associate's Degree",2);
insert into WORK_EXPERIENCE values (NULL,"Solicitor","2016-06-28","2016-07-05","Reyes, Duran and Lin","Nesciunt nam assumenda minima minus laudantium. Consectetur incidunt libero provident officia possimus. Expedita numquam tenetur pariatur sequi sapiente laboriosam quia esse.",2);
insert into WORK_EXPERIENCE values (NULL,"Pilot, airline","2016-06-05","2016-01-17","Schaefer-Buchanan","Placeat occaecati corrupti beatae porro. Recusandae odio iusto adipisci minus ullam ducimus soluta. Unde quo labore ducimus ipsum dolorem rerum.",2);
insert into JOB_SEEKER values (3, "jamesparker@gmail.com", "74Z52Fvdp", "Sequi non pariatur hic nihil facere. Praesentium incidunt qui ratione cum placeat. Reprehenderit quia at ipsum nemo facere rem est id.", CURDATE(), CURDATE(), "2016-10-09", "86776049897", "female", "Ora", "Albrecht", "Pope", "849 Massey Drive", "Millsland", "Cuba");
insert into JOB_SEEKER_SKILL values (3,"Senior tax professional/tax inspector");
insert into JOB_SEEKER_SKILL values (3,"Museum/gallery curator");
insert into JOB_SEEKER_SKILL values (3,"Veterinary surgeon");
insert into JOB_SEEKER_SKILL values (3,"Industrial buyer");
insert into JOB_SEEKER_SKILL values (3,"Advertising account executive");
insert into JOB_SEEKER_SKILL values (3,"Transport planner");
insert into EDUCATION values (NULL,"Molestias suscipit est maxime illum. Nemo illum praesentium sint nulla illo dolore. Tempora repudiandae natus maxime harum alias impedit.","Lovett University","2016-09-04","2016-01-09","Doctorate",3);
insert into EDUCATION values (NULL,"Dignissimos sed enim rem eligendi. Accusamus quas autem illum accusantium sapiente ipsa occaecati. Fugit odio impedit eum.","Martinez University","2016-05-04","2016-06-05","Bachelor's Degree",3);
insert into WORK_EXPERIENCE values (NULL,"Lighting technician, broadcasting/film/video","2016-04-20","2016-05-18","Kim, Barnes and Hoffman","Inventore numquam ullam id quos recusandae deleniti. Hic deserunt repellat sunt quia. Incidunt minima autem quasi quos sapiente.",3);
insert into WORK_EXPERIENCE values (NULL,"Radio producer","2016-06-05","2016-06-12","Brown-Miller","Voluptates natus laborum nesciunt ex molestias placeat molestiae numquam. Quaerat porro odit esse natus. Laborum reprehenderit voluptatum non odio. Tempora ut ex rerum quibusdam.",3);
insert into WORK_EXPERIENCE values (NULL,"Private music teacher","2016-10-11","2016-09-09","Hansen, Patrick and Brown","Laborum cum molestiae dolores quisquam inventore tenetur culpa. Doloremque magnam facere nostrum rem. Quibusdam corporis fuga quisquam quis possimus. Odio soluta inventore at modi.",3);
insert into JOB_SEEKER values (4, "gonzalezaaron@holmes.org", "64ipQRIK", "Voluptate laudantium minima omnis nemo porro. Aliquid magnam corrupti sequi pariatur voluptates nulla possimus.", CURDATE(), CURDATE(), "2016-10-08", "60268681614", "female", "Mary", "Azar", "Fleischman", "7927 Miller Loaf", "East Sethhaven", "Russian Federation");
insert into JOB_SEEKER_SKILL values (4,"Public librarian");
insert into JOB_SEEKER_SKILL values (4,"Field trials officer");
insert into JOB_SEEKER_SKILL values (4,"Acupuncturist");
insert into JOB_SEEKER_SKILL values (4,"Music tutor");
insert into JOB_SEEKER_SKILL values (4,"Copy");
insert into JOB_SEEKER_SKILL values (4,"Probation officer");
insert into EDUCATION values (NULL,"Accusamus id facilis at sequi. Aliquid eius corporis nobis similique ad cum. Voluptatibus aliquid illum dolore quo voluptatibus inventore est.","Clay School","2016-09-04","2016-06-08","Associate's Degree",4);
insert into EDUCATION values (NULL,"Tenetur minus deserunt tempore vitae. Assumenda rem repellat quidem iusto. Reprehenderit laborum vitae laborum aspernatur corporis non. Quod voluptate rem distinctio aperiam soluta.","Halstead School","2016-06-20","2016-06-20","High School",4);
insert into EDUCATION values (NULL,"Fugit nesciunt debitis eveniet et accusamus nisi. Provident accusamus facilis maiores.","Greis University","2016-07-28","2016-08-01","Doctorate",4);
insert into WORK_EXPERIENCE values (NULL,"Production assistant, television","2016-01-05","2016-05-21","Smith PLC","Quisquam nam ipsam ex nemo quaerat ipsam ipsum. Ad neque sunt tenetur quam nobis corporis cum. Quisquam magni ratione magni eius. Fugiat expedita quidem suscipit optio nihil pariatur.",4);
insert into WORK_EXPERIENCE values (NULL,"Runner, broadcasting/film/video","2016-07-14","2016-09-03","Cole-Brooks","Sunt necessitatibus libero corporis unde id. Debitis modi odio mollitia exercitationem distinctio veniam. Velit in impedit ea. Quidem enim molestias culpa.",4);
insert into WORK_EXPERIENCE values (NULL,"Insurance claims handler","2016-05-22","2016-05-14","Thompson, Roach and Edwards","Ex non dolor quo. Placeat voluptatibus atque maiores facere eaque magnam. Aperiam itaque illum id alias facilis eveniet ab. Praesentium nemo nam qui eaque nisi.",4);
insert into JOB_SEEKER values (5, "hamiltonbruce@cox-rivera.com", "dKyxp1KW", "Soluta recusandae dolore commodi fugit laboriosam. Laboriosam quibusdam eligendi ullam placeat asperiores. Cumque necessitatibus magni fugiat cum.", CURDATE(), CURDATE(), "2016-04-04", "28427780445", "male", "Jimmy", "Santistevan", "Miller", "98539 Cook Skyway Apt. 035", "Hicksburgh", "Maldives");
insert into JOB_SEEKER_SKILL values (5,"Engineer");
insert into JOB_SEEKER_SKILL values (5,"Designer");
insert into JOB_SEEKER_SKILL values (5,"Police officer");
insert into JOB_SEEKER_SKILL values (5,"Therapeutic radiographer");
insert into JOB_SEEKER_SKILL values (5,"Tax inspector");
insert into EDUCATION values (NULL,"Aliquam est sunt nisi totam. Veritatis veritatis facere numquam amet.
Adipisci qui iusto eos delectus. Reiciendis optio tenetur numquam beatae doloribus possimus. In fuga vitae vel ducimus ipsa id.","Walrath Institution","2016-11-06","2016-11-09","Associate's Degree",5);
insert into EDUCATION values (NULL,"Sequi temporibus provident quaerat quod. Qui nesciunt ipsa possimus illo minima. Nam praesentium cupiditate perspiciatis.","Duran University","2016-07-04","2016-03-06","High School",5);
insert into WORK_EXPERIENCE values (NULL,"Medical sales representative","2016-01-17","2016-03-27","Coleman PLC","Iure dolorum dolore neque tenetur. Commodi exercitationem culpa aliquam porro. Officia doloribus illum vitae dolorum laborum minima. Voluptate recusandae excepturi dolorem.",5);
insert into WORK_EXPERIENCE values (NULL,"Engineer, manufacturing systems","2016-06-15","2016-07-09","Flores-Gutierrez","Incidunt porro placeat doloremque odit magni. Cum repellendus vero ipsa praesentium expedita.",5);
insert into WORK_EXPERIENCE values (NULL,"Engineer, control and instrumentation","2016-11-04","2016-09-03","Olson PLC","In quia itaque alias veniam nulla placeat soluta. Repellendus quas recusandae asperiores fugit maiores natus. Error repellendus id pariatur sunt.",5);
insert into WORK_EXPERIENCE values (NULL,"Retail banker","2016-09-15","2016-06-26","Murray-Levy","Facilis ea accusamus cumque tenetur aperiam esse. Rerum eius tempore et hic. Maiores excepturi libero pariatur est.",5);
insert into JOB_SEEKER values (6, "nelsonsean@anderson.com", "7h2LKOsx", "Facere quis eum iure quibusdam quis possimus. Tenetur rem harum vel aspernatur error doloribus.", CURDATE(), CURDATE(), "2016-06-17", "36892761247", "male", "Anthony", "Kallevig", "Rosboril", "114 Joyce Pines Suite 775", "South Angela", "Svalbard & Jan Mayen Islands");
insert into JOB_SEEKER_SKILL values (6,"Medical physicist");
insert into JOB_SEEKER_SKILL values (6,"Scientist");
insert into JOB_SEEKER_SKILL values (6,"Production engineer");
insert into JOB_SEEKER_SKILL values (6,"Research scientist (maths)");
insert into JOB_SEEKER_SKILL values (6,"Surveyor");
insert into JOB_SEEKER_SKILL values (6,"Investment banker");
insert into EDUCATION values (NULL,"Aliquid dolores reiciendis culpa quae. Tempore ullam ipsum dolor eum dolores necessitatibus doloremque mollitia.","Clark Institution","2016-10-27","2016-02-29","High School",6);
insert into EDUCATION values (NULL,"Sint voluptate nam aut reprehenderit iure ut facilis. Laudantium exercitationem nihil ipsa laudantium. Et quis soluta fugiat nisi ipsum.","Short University","2016-08-22","2016-02-29","Bachelor's Degree",6);
insert into EDUCATION values (NULL,"Blanditiis possimus similique minus fuga cupiditate qui corporis. Corrupti adipisci possimus nemo temporibus cumque hic. Cumque ab sapiente repellendus tenetur ut beatae.","Friedman University","2016-01-29","2016-08-30","Master's Degree",6);
insert into WORK_EXPERIENCE values (NULL,"Therapist, drama","2016-10-14","2016-11-07","Gonzalez Inc","Mollitia vitae at ipsa quaerat quibusdam consequatur laudantium. Adipisci labore porro quo cupiditate saepe. Porro debitis architecto atque temporibus iste.",6);
insert into WORK_EXPERIENCE values (NULL,"Engineer, petroleum","2016-09-05","2016-06-11","Gates-Mcclain","Voluptatum quod voluptates quos esse. Placeat doloribus temporibus maxime cumque illum. Dolore accusantium maiores deleniti expedita soluta reiciendis ipsam.",6);
insert into WORK_EXPERIENCE values (NULL,"Forest/woodland manager","2016-09-21","2016-04-17","Ferguson and Sons","Libero adipisci non labore. Dolore distinctio sit alias. Harum delectus recusandae vel mollitia at vitae.",6);
insert into WORK_EXPERIENCE values (NULL,"IT trainer","2016-01-22","2016-03-10","Riggs-Edwards","Commodi earum ut culpa placeat itaque numquam saepe. Debitis veritatis facere ad perspiciatis officia libero. Qui minima error et.",6);
insert into JOB_SEEKER values (7, "tarashea@yoder.com", "wLKb3vl", "Numquam deserunt molestiae nostrum. Porro modi consectetur voluptatum voluptatum natus laudantium distinctio.", CURDATE(), CURDATE(), "2016-01-17", "79626704092", "male", "Chase", "Poage", "Griffin", "5733 Christopher Shoal", "Brandibury", "Cocos (Keeling) Islands");
insert into JOB_SEEKER_SKILL values (7,"Geochemist");
insert into JOB_SEEKER_SKILL values (7,"Engineer");
insert into JOB_SEEKER_SKILL values (7,"Surveyor");
insert into JOB_SEEKER_SKILL values (7,"Agricultural engineer");
insert into JOB_SEEKER_SKILL values (7,"Interior and spatial designer");
insert into EDUCATION values (NULL,"Incidunt sint molestias minus error. Quisquam quod ut modi sed veniam.
Soluta alias quam minima aspernatur. Officia eligendi neque neque sit iusto est. At facere animi exercitationem omnis.","Boyle Institution","2016-04-09","2016-04-13","Doctorate",7);
insert into EDUCATION values (NULL,"Vero dolor facilis magnam. Ipsa nulla architecto vero corrupti. Non a tenetur magnam magni. Magni tempore consequuntur dolor minima.","Ramirez University","2016-11-06","2016-09-12","High School",7);
insert into EDUCATION values (NULL,"Laboriosam minus doloribus voluptatum vitae id asperiores modi. Voluptate ullam consequatur corporis perferendis dolores in. Deleniti ea animi aperiam possimus ut unde.","Grimes Institution","2016-06-26","2016-10-08","Vocational Course",7);
insert into EDUCATION values (NULL,"Dolorem architecto dolore dolores eveniet nesciunt. Harum dolorem aliquam id modi fuga odio. Deleniti blanditiis voluptate voluptate eius ab quae harum. Ad voluptatibus suscipit eveniet earum.","Hicks Institution","2016-09-29","2016-01-17","Vocational Course",7);
insert into WORK_EXPERIENCE values (NULL,"Tax adviser","2016-10-24","2016-10-18","Rollins LLC","Omnis pariatur temporibus nostrum ab dolores id. Nisi quia nam quasi incidunt. Animi saepe fugiat esse tenetur consectetur.",7);
insert into WORK_EXPERIENCE values (NULL,"Civil Service administrator","2016-10-25","2016-02-24","Martinez-Perez","Quis commodi officiis deserunt deserunt autem eum. Accusantium eligendi totam ipsam dolore. Eaque dolores provident iusto sapiente sint quisquam. Assumenda odit odit repellat et harum.",7);
insert into WORK_EXPERIENCE values (NULL,"Clinical embryologist","2016-07-17","2016-11-18","Esparza Inc","Eos veritatis porro cupiditate sint. Dolores odit est tempore voluptatum asperiores quos magni vero. Quasi aut nesciunt molestias placeat. Suscipit vero deleniti ducimus tempora ad ratione saepe.",7);
insert into JOB_SEEKER values (8, "jacqueline06@sanchez-payne.com", "46OGn8I", "Quidem dignissimos maiores facere illum. Nisi unde porro aperiam est nihil error. Quis quibusdam laudantium necessitatibus repellat.", CURDATE(), CURDATE(), "2016-11-24", "83076738245", "male", "Lesley", "Cornwell", "Cohn", "1435 Cody Centers Apt. 957", "Scotthaven", "Sweden");
insert into JOB_SEEKER_SKILL values (8,"Operations geologist");
insert into JOB_SEEKER_SKILL values (8,"Secretary");
insert into JOB_SEEKER_SKILL values (8,"Development worker");
insert into JOB_SEEKER_SKILL values (8,"Surveyor");
insert into JOB_SEEKER_SKILL values (8,"Television camera operator");
insert into JOB_SEEKER_SKILL values (8,"Academic librarian");
insert into EDUCATION values (NULL,"Velit vero harum itaque iusto sapiente. Aut alias nesciunt ad dicta nemo animi. Maxime ad distinctio praesentium ut iure nam ab.","Lanier School","2016-09-13","2016-02-07","Vocational Course",8);
insert into EDUCATION values (NULL,"Quis eligendi repellendus quibusdam. Accusamus laudantium nihil eum corrupti saepe. Magni quisquam deserunt earum corrupti.","Rhodes University","2016-10-14","2016-02-20","Doctorate",8);
insert into EDUCATION values (NULL,"Possimus cumque assumenda nam recusandae earum alias tempore. Tempore voluptas odio natus ullam neque id cupiditate. Earum aspernatur unde inventore ratione. Nihil provident voluptates corporis.","Miller Institution","2016-05-17","2016-08-22","Doctorate",8);
insert into EDUCATION values (NULL,"Magni distinctio adipisci unde veniam. Repellendus debitis in repellat est ducimus quis ratione.","Thacker School","2016-05-14","2016-06-21","Bachelor's Degree",8);
insert into WORK_EXPERIENCE values (NULL,"Optician, dispensing","2016-02-22","2016-03-17","Rodriguez Group","Odio atque sed molestias harum architecto eveniet consequatur. Sed qui dolore aliquam sapiente. Quisquam unde impedit labore magni voluptatem corporis.",8);
insert into WORK_EXPERIENCE values (NULL,"Medical sales representative","2016-05-14","2016-08-29","Frederick, Pierce and Bailey","Quam voluptates assumenda soluta incidunt illum dolores itaque. Quam minima vero deserunt earum architecto facere hic modi.",8);
insert into JOB_SEEKER values (9, "garywarren@jones-young.com", "As7tz4Tzd", "Delectus impedit veritatis hic voluptate fugiat amet omnis. Deleniti ipsum amet maiores reiciendis. Fugit tempore ipsam sed neque aliquam.", CURDATE(), CURDATE(), "2016-03-17", "30975198608", "male", "Joshua", "Carr", "Carbone", "9151 Duke Mountains", "Hubermouth", "Greenland");
insert into JOB_SEEKER_SKILL values (9,"Company secretary");
insert into JOB_SEEKER_SKILL values (9,"Accountant");
insert into JOB_SEEKER_SKILL values (9,"Midwife");
insert into JOB_SEEKER_SKILL values (9,"Toxicologist");
insert into JOB_SEEKER_SKILL values (9,"Product designer");
insert into JOB_SEEKER_SKILL values (9,"Market researcher");
insert into EDUCATION values (NULL,"Laborum provident accusamus libero sed delectus quidem atque veritatis. Cumque labore maxime ipsum nostrum eaque modi. Id ratione saepe perspiciatis voluptates iusto consequatur voluptatibus.","Ornelas School","2016-05-29","2016-04-20","High School",9);
insert into EDUCATION values (NULL,"Aspernatur cupiditate totam pariatur. Fugit corrupti ut harum ab maiores. Temporibus veritatis officiis ea beatae quaerat praesentium dolorem. Nesciunt repudiandae adipisci cupiditate.","Burns Institution","2016-09-11","2016-08-20","Bachelor's Degree",9);
insert into EDUCATION values (NULL,"Est quas commodi quibusdam quasi animi iure sed impedit. Ad ducimus id molestias. Velit minima saepe quaerat eius labore. Similique velit perferendis numquam eaque blanditiis repudiandae.","Marr School","2016-01-01","2016-06-05","High School",9);
insert into EDUCATION values (NULL,"Quas in ex nobis hic eaque ratione. Dignissimos tempora odio aspernatur ut. Eaque officiis hic nobis.","Stolar Institution","2016-01-08","2016-04-25","Master's Degree",9);
insert into WORK_EXPERIENCE values (NULL,"Clothing/textile technologist","2016-02-12","2016-10-14","Christian-Harmon","Temporibus sit porro impedit. Ex dolor consequuntur perspiciatis eos possimus cupiditate quo. Vero quam harum quos consectetur laborum ut.",9);
insert into WORK_EXPERIENCE values (NULL,"Systems analyst","2016-07-07","2016-08-30","Turner Group","Modi animi harum blanditiis. Repudiandae neque architecto aperiam cum. Nesciunt facilis unde dolor nostrum nemo omnis. Voluptatibus dolorum assumenda distinctio quos dolorem amet vero.",9);
insert into WORK_EXPERIENCE values (NULL,"Secretary/administrator","2016-02-04","2016-07-28","Robinson PLC","Distinctio fugiat at quo voluptas dicta sed. Asperiores maiores porro incidunt voluptas. Laudantium sit ex consequatur vitae. Saepe vero voluptate pariatur.",9);
insert into WORK_EXPERIENCE values (NULL,"Animal technologist","2016-06-30","2016-06-28","Cox and Sons","Occaecati cupiditate molestiae adipisci cum. Temporibus deserunt voluptas eos mollitia impedit explicabo veritatis excepturi. Corporis ex fuga ratione voluptates ut voluptatum quaerat.",9);
insert into JOB_SEEKER values (10, "michaelmcguire@oliver.com", "6D1IIyR7", "Adipisci magni quis earum id commodi at hic ipsa. Dolorem est minima velit veritatis. Consectetur iure quod iusto facere iste debitis. Officia sed eaque incidunt unde accusamus.", CURDATE(), CURDATE(), "2016-10-17", "81184118603", "female", "Monika", "Swagerty", "Kalar", "78453 Pamela Throughway", "Davidburgh", "Turks and Caicos Islands");
insert into JOB_SEEKER_SKILL values (10,"Counsellor");
insert into JOB_SEEKER_SKILL values (10,"Actor");
insert into JOB_SEEKER_SKILL values (10,"Illustrator");
insert into JOB_SEEKER_SKILL values (10,"Metallurgist");
insert into JOB_SEEKER_SKILL values (10,"Therapist");
insert into EDUCATION values (NULL,"Quo vel dolore impedit odit quas exercitationem quis iusto. Illo aliquam qui exercitationem maxime delectus. Repellendus accusamus perferendis sit nulla esse saepe.","Wathen University","2016-05-22","2016-09-25","Bachelor's Degree",10);
insert into EDUCATION values (NULL,"Non ipsa exercitationem dolor quos vel commodi nisi. Consectetur provident dolores modi totam ullam. Nobis magni ipsa neque accusantium.","Cassel University","2016-10-29","2016-05-12","Vocational Course",10);
insert into EDUCATION values (NULL,"Est quo cupiditate numquam assumenda veritatis atque. Id aut neque incidunt vel. Veritatis officiis debitis voluptatum eius labore alias quibusdam. Harum culpa aliquid eligendi quaerat.","Carranza School","2016-10-04","2016-02-03","Associate's Degree",10);
insert into EDUCATION values (NULL,"Saepe eos recusandae quis corrupti expedita. Suscipit ipsum aspernatur sapiente sit saepe vel. A modi placeat ratione ut magnam quos sit.","Ellison School","2016-05-19","2016-09-08","Doctorate",10);
insert into WORK_EXPERIENCE values (NULL,"Engineer, site","2016-09-01","2016-07-26","Smith Inc","Eaque repudiandae exercitationem eum. Laudantium quaerat id sunt inventore amet ex a. Adipisci pariatur in eveniet quasi repellat in dolorum quas.",10);
insert into WORK_EXPERIENCE values (NULL,"Conservation officer, historic buildings","2016-07-24","2016-08-12","Davis Inc","Rem tempore quis tenetur culpa. Soluta eaque maxime quaerat illum sint corrupti repudiandae nam.",10);
insert into WORK_EXPERIENCE values (NULL,"Fitness centre manager","2016-10-28","2016-10-08","Ayala-Moore","Quia quidem tempore tenetur dolores provident. Magni fugit iste in cupiditate quia inventore. Harum sed voluptate perferendis reprehenderit.",10);
