use jobFinder;
delete from JOB;
ALTER TABLE JOB AUTO_INCREMENT = 0;
insert into JOB values (NULL, "Human resources officer", "Perferendis sapiente officiis voluptate unde voluptate fugiat. Provident perferendis eum ipsa veritatis quo. Laboriosam delectus reiciendis harum eligendi dignissimos sunt.", "Part-time", "Associate / Supervisor", "77000", "2016-03-30", "Other", "67829 Wong Creek", "Hughesshire", "Saint Pierre and Miquelon", "2016-08-12", 4);
insert into REQUIREMENT values (NULL,"Master's Degree", 1);
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Contracting civil engineer");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Ecologist");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Teacher");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Clinical biochemist");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Printmaker");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Development worker");
insert into JOB values (NULL, "Corporate investment banker", "Quis hic quaerat ut sint aut. Deleniti corporis eveniet sunt asperiores explicabo quis quo. Pariatur perferendis magni dolores expedita iure reiciendis.", "Part-time", "Associate / Supervisor", "35000", "2016-10-24", "Energy and utilities", "21517 Sara Terrace", "East Bobbyland", "Jamaica", "2016-05-23", 10);
insert into REQUIREMENT values (NULL,"Doctorate", 2);
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Press photographer");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Education officer");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Emergency planning/management officer");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Actuary");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Environmental consultant");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Radiation protection practitioner");
insert into JOB values (NULL, "Charity officer", "Quidem repudiandae ex magnam cumque. Vero tempora sit at. Corrupti totam deleniti sint.", "Part-time", "Mid-Senior Level / Manager", "29000", "2016-06-02", "Environment and agriculture", "246 Campos Flat", "East Kylestad", "Tajikistan", "2016-07-22", 2);
insert into REQUIREMENT values (NULL,"Bachelor's Degree", 3);
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Engineer");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Estate manager/land agent");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Librarian");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Editor");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Surveyor");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Land/geomatics surveyor");
insert into JOB values (NULL, "Primary school teacher", "Vitae impedit voluptate saepe quibusdam numquam excepturi. Autem possimus laborum ipsam. Non ipsam fugit distinctio asperiores. Illo perspiciatis asperiores quos unde.", "Part-time", "Director / Executive", "73000", "2016-06-18", "Law", "5319 Scott Meadow Apt. 335", "South Tamifort", "Syrian Arab Republic", "2016-08-13", 7);
insert into REQUIREMENT values (NULL,"Master's Degree", 4);
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Government social research officer");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Therapist");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Engineer");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Heritage manager");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Horticultural therapist");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Clinical psychologist");
insert into JOB values (NULL, "Toxicologist", "Iusto delectus consequatur accusantium itaque. Tempore nobis quaerat alias aliquam impedit cum. Nihil occaecati cum corrupti id odio eaque. Officiis quidem aut quo deserunt possimus officiis fugiat.", "Part-time", "Internship / OJT", "71000", "2016-10-05", "Healthcare", "0006 King Grove", "Port Michaeltown", "Rwanda", "2016-02-07", 5);
insert into REQUIREMENT values (NULL,"Associate's Degree", 5);
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Psychologist");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Analytical chemist");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Medical physicist");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Actuary");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Rural practice surveyor");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Multimedia programmer");
insert into JOB values (NULL, "Special educational needs teacher", "Officia quae quisquam illo natus consequatur natus error. Amet repudiandae harum ipsam eaque quos cupiditate.", "Part-time", "Mid-Senior Level / Manager", "17000", "2016-10-24", "Leisure, sport and tourism", "8146 Patrick Inlet", "Port Timothy", "Canada", "2016-09-16", 3);
insert into REQUIREMENT values (NULL,"Bachelor's Degree", 6);
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Therapist");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Embryologist");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Financial risk analyst");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Optometrist");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Hospital doctor");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Newspaper journalist");
insert into JOB values (NULL, "Curator", "Ad similique suscipit delectus a omnis explicabo dolorum similique. Saepe eos exercitationem corporis. Officiis quod debitis vitae dolore mollitia.", "Full-time", "Internship / OJT", "98000", "2016-06-06", "Healthcare", "226 Carl Stream Apt. 718", "Theresaport", "Tokelau", "2016-10-06", 1);
insert into REQUIREMENT values (NULL,"Doctorate", 7);
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Microbiologist");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Research officer");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Public relations officer");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Programme researcher");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Surveyor");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Ceramics designer");
insert into JOB values (NULL, "Broadcast journalist", "Dicta minus corrupti eaque ipsum ad fuga neque perspiciatis. Non nulla quis ratione totam id placeat tenetur. Impedit aliquam qui provident eaque.", "Full-time", "Associate / Supervisor", "94000", "2016-10-22", "Public services and administration", "955 Tyler Harbor Apt. 986", "Lake Sarah", "Greece", "2016-10-15", 1);
insert into REQUIREMENT values (NULL,"Vocational Course", 8);
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Logistics and distribution manager");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Engineer");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Electrical engineer");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Best boy");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Nutritional therapist");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Arts administrator");
insert into JOB values (NULL, "Orthoptist", "Molestias quibusdam delectus blanditiis dicta aliquam. Reprehenderit sed non odio magnam quae maiores. Beatae eum voluptas accusantium atque impedit laudantium dolorem.", "Full-time", "Mid-Senior Level / Manager", "89000", "2016-11-07", "Leisure, sport and tourism", "9106 James Burg Apt. 676", "Jenniferview", "Russian Federation", "2016-08-29", 3);
insert into REQUIREMENT values (NULL,"Master's Degree", 9);
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Community pharmacist");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Midwife");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Field seismologist");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Fashion designer");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Human resources officer");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Adult guidance worker");
insert into JOB values (NULL, "Designer, fashion/clothing", "Provident nihil excepturi corrupti sed assumenda. Fuga voluptate vero non libero. Architecto ea ipsum odio voluptate quis fuga earum.", "Full-time", "Director / Executive", "34000", "2016-06-07", "Public services and administration", "0851 Tyler Loop Apt. 089", "North Nicole", "Guatemala", "2016-02-19", 5);
insert into REQUIREMENT values (NULL,"Bachelor's Degree", 10);
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Therapist");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Data processing manager");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Insurance account manager");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Civil engineer");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"Product designer");
insert into REQUIREMENT_SKILL values (LAST_INSERT_ID(),"IT trainer");
