use jobFinder;
delete from JOB_SEEKER;
ALTER TABLE JOB_SEEKER AUTO_INCREMENT = 0;
insert into JOB_SEEKER values (1, "collinskevin@lane.biz", "CMrlCX2", "Iusto voluptatum ipsum repellat doloremque. Veniam ipsa quis doloribus distinctio. Asperiores unde commodi aliquam autem mollitia. Ipsa temporibus a iusto at.", CURDATE(), CURDATE(), "2016-01-31", "55196690785", "female", "Belinda", "Brazil", "Brown", "89838 Davis Falls", "Wandashire", "Belgium");
insert into JOB_SEEKER_SKILL values (1,"Journalist");
insert into JOB_SEEKER_SKILL values (1,"Advice worker");
insert into JOB_SEEKER_SKILL values (1,"Food technologist");
insert into JOB_SEEKER_SKILL values (1,"Trade mark attorney");
insert into JOB_SEEKER_SKILL values (1,"Academic librarian");
insert into JOB_SEEKER_SKILL values (1,"Occupational psychologist");
insert into EDUCATION values (NULL,"Eum facere quaerat perferendis adipisci autem aperiam. Delectus sequi illo voluptas at ipsa enim corporis. Impedit dolorum minus quasi facere esse hic.","Hall School","2016-08-16","2016-07-01","Vocational Course",1);
insert into EDUCATION values (NULL,"Praesentium maxime neque quod facilis dolor. Autem ex rem ipsam assumenda.","Haviland School","2016-03-24","2016-01-02","Master's Degree",1);
insert into EDUCATION values (NULL,"Laboriosam a ducimus aliquid dolorum reprehenderit. Ipsam corporis aut magni a nemo occaecati tempore sint. Hic aperiam et quis recusandae veniam veritatis optio excepturi.","Smith School","2016-04-24","2016-01-06","Associate's Degree",1);
insert into WORK_EXPERIENCE values (NULL,"Quantity surveyor","Larsen, Castro and Smith","2016-02-09","2016-04-27","Eum mollitia deserunt accusamus unde ducimus amet. Consectetur beatae exercitationem voluptatem nostrum. Repudiandae recusandae ducimus ipsa.",1);
insert into WORK_EXPERIENCE values (NULL,"Merchandiser, retail","Brown Ltd","2016-04-09","2016-01-08","Ut id nam nulla cumque ullam. Maiores officia explicabo facere totam voluptatem.
Facere neque cum minima iste ipsam accusantium minus. Nisi dicta corrupti expedita dolores.",1);
insert into WORK_EXPERIENCE values (NULL,"Haematologist","Summers-Holloway","2016-06-28","2016-10-07","Dignissimos fugit dicta rem maxime nostrum nesciunt. Veniam reprehenderit ipsum optio exercitationem numquam quisquam.",1);
insert into JOB_SEEKER values (2, "qhendrix@garcia-nguyen.com", "6iHjqInhKy", "Tempora illum dolor ullam eligendi neque suscipit. Velit asperiores laboriosam quisquam. Ut blanditiis hic veniam quisquam non. Fugit praesentium perferendis doloribus laborum.", CURDATE(), CURDATE(), "2016-09-24", "36288841084", "male", "Peter", "Blair", "Martinez", "2426 Moreno Isle Apt. 911", "Lake Markfort", "Holy See (Vatican City State)");
insert into JOB_SEEKER_SKILL values (2,"Theatre manager");
insert into JOB_SEEKER_SKILL values (2,"Medical illustrator");
insert into JOB_SEEKER_SKILL values (2,"Ecologist");
insert into JOB_SEEKER_SKILL values (2,"Sports coach");
insert into JOB_SEEKER_SKILL values (2,"Call centre manager");
insert into JOB_SEEKER_SKILL values (2,"Dentist");
insert into EDUCATION values (NULL,"Totam modi architecto mollitia necessitatibus asperiores inventore corrupti. Nemo occaecati optio explicabo quasi esse iste. Quisquam quae asperiores nostrum suscipit iste minima ipsam.","Pickett School","2016-05-04","2016-02-22","Bachelor's Degree",2);
insert into EDUCATION values (NULL,"Blanditiis assumenda nostrum voluptas itaque magnam vero. Nobis non impedit incidunt velit omnis. Facere libero numquam dolor. Ab voluptate numquam mollitia voluptas.","Davis Institution","2016-01-16","2016-03-27","Master's Degree",2);
insert into EDUCATION values (NULL,"Laudantium quam animi debitis accusamus. Magni consequatur natus saepe rem adipisci atque. Saepe eaque consectetur magni tenetur perspiciatis enim. Reiciendis unde sint quas.","Barton Institution","2016-06-27","2016-08-26","Doctorate",2);
insert into EDUCATION values (NULL,"Cumque minus ducimus eaque quia maxime veritatis. Ipsum necessitatibus voluptatem dolor ipsam ex porro sapiente. Atque voluptate ipsam ipsa consectetur inventore.","Davis Institution","2016-03-16","2016-09-06","Vocational Course",2);
insert into WORK_EXPERIENCE values (NULL,"Education officer, environmental","Allen and Sons","2016-01-05","2016-03-15","Ipsum consequuntur asperiores quo impedit iste. Minima et a in deleniti omnis quidem expedita. Esse veniam ad veritatis ab labore nostrum.",2);
insert into WORK_EXPERIENCE values (NULL,"Clinical embryologist","Miller-Garrett","2016-10-25","2016-01-07","Est ab aliquid fugiat dicta libero est cumque. Dolorum dicta beatae consequatur quod commodi fuga quas. Dicta vel fugit fugit modi officia. Similique sunt neque dicta est iusto aliquid earum.",2);
insert into WORK_EXPERIENCE values (NULL,"Economist","Carter-Ingram","2016-07-21","2016-08-29","Voluptatum officiis laborum ipsam quam amet. Magni neque reprehenderit illum. Sit quos temporibus placeat quas cupiditate est illum. Asperiores mollitia quisquam laborum odio aperiam.",2);
insert into WORK_EXPERIENCE values (NULL,"Chartered legal executive (England and Wales)","Perez, Hansen and Hill","2016-11-15","2016-07-11","Aliquid quae ipsum nam reprehenderit iusto corrupti cumque. Facere sint quod ipsam ipsam est dolor ad doloribus. Doloribus odit aspernatur odit maiores doloribus quia.",2);
insert into JOB_SEEKER values (3, "tracyboone@wiggins.com", "cJhS7BL", "Earum quis impedit repudiandae commodi cumque eum. Libero sunt placeat blanditiis asperiores at modi quod. Odio incidunt rerum magni omnis cumque iusto.", CURDATE(), CURDATE(), "2016-11-16", "45924941746", "female", "Artie", "Lopez", "Williams", "41559 Jennifer Radial Suite 984", "East Amber", "Pitcairn Islands");
insert into JOB_SEEKER_SKILL values (3,"Regulatory affairs officer");
insert into JOB_SEEKER_SKILL values (3,"Surgeon");
insert into JOB_SEEKER_SKILL values (3,"Nutritional therapist");
insert into JOB_SEEKER_SKILL values (3,"Arboriculturist");
insert into JOB_SEEKER_SKILL values (3,"Lobbyist");
insert into JOB_SEEKER_SKILL values (3,"Financial planner");
insert into EDUCATION values (NULL,"Optio laudantium occaecati alias pariatur distinctio. Alias quae repudiandae nihil sed.","Borsellino Institution","2016-01-09","2016-08-24","Doctorate",3);
insert into EDUCATION values (NULL,"Id at voluptates rem velit repellendus autem maiores. Autem in consectetur officia. Incidunt qui sit nihil corrupti aperiam.","Maloney University","2016-09-20","2016-10-31","Associate's Degree",3);
insert into EDUCATION values (NULL,"Doloribus corrupti laudantium voluptate distinctio. Sit mollitia in cumque illum dignissimos optio culpa. Soluta deleniti adipisci alias dolor iusto distinctio.","Weir University","2016-06-24","2016-05-19","Vocational Course",3);
insert into WORK_EXPERIENCE values (NULL,"Operational investment banker","Delgado, Ramirez and Ruiz","2016-07-05","2016-01-11","Ipsam illum placeat dolorum sapiente esse. Officiis minus tenetur voluptates. Ex ullam esse nisi deleniti culpa facere quae.",3);
insert into WORK_EXPERIENCE values (NULL,"Graphic designer","Richardson, Johnson and Romero","2016-04-14","2016-06-21","Facilis commodi est tempore saepe sit harum maxime. Libero est illum libero asperiores. Accusamus nostrum amet adipisci corrupti cumque exercitationem.",3);
insert into JOB_SEEKER values (4, "rodriguezdaniel@yahoo.com", "KQmFsY", "Distinctio totam harum autem natus consectetur. Totam cum distinctio ea tenetur vitae quo nulla. Laudantium distinctio doloribus qui. Minima laudantium rerum modi ipsa voluptatem esse dolorum.", CURDATE(), CURDATE(), "2016-10-23", "78912493508", "male", "Gregory", "Bickham", "Smith", "736 Leslie Drives Apt. 231", "Ericview", "Guernsey");
insert into JOB_SEEKER_SKILL values (4,"Make");
insert into JOB_SEEKER_SKILL values (4,"Insurance risk surveyor");
insert into JOB_SEEKER_SKILL values (4,"Stage manager");
insert into JOB_SEEKER_SKILL values (4,"Radiographer");
insert into JOB_SEEKER_SKILL values (4,"Producer");
insert into JOB_SEEKER_SKILL values (4,"Archaeologist");
insert into EDUCATION values (NULL,"Animi sed ea est quaerat itaque necessitatibus exercitationem. Laborum eos aspernatur maxime eligendi nisi dicta. Natus sint vitae fuga ducimus.","Ronzoni Institution","2016-01-29","2016-04-07","Doctorate",4);
insert into EDUCATION values (NULL,"Consequuntur at cupiditate laborum natus nulla placeat. Veniam repellendus numquam molestias voluptates quia ex vel. Veniam possimus beatae ea similique libero.","Lawley University","2016-04-22","2016-02-19","Bachelor's Degree",4);
insert into WORK_EXPERIENCE values (NULL,"Occupational psychologist","Walker-Long","2016-03-22","2016-02-14","Sint ipsa aliquid libero sequi eum dolorum aliquid. Doloremque ad maxime optio aperiam in earum culpa. Odio sunt explicabo pariatur quidem aliquam. Similique commodi quae quidem tenetur nesciunt.",4);
insert into WORK_EXPERIENCE values (NULL,"Physicist, medical","Crosby Ltd","2016-05-06","2016-04-28","Vero ex accusamus reprehenderit quia odio accusantium. Placeat cumque debitis eaque sequi delectus. Cum quidem libero quaerat reprehenderit occaecati eum.",4);
insert into JOB_SEEKER values (5, "danielbell@daniel.com", "mLsw4ZXN1", "Repellendus inventore doloribus magnam. Sunt placeat dolore corrupti ullam possimus aliquid.", CURDATE(), CURDATE(), "2016-09-16", "67782306357", "female", "Gina", "Johnson", "Collman", "57750 Patterson Keys Suite 347", "Lake Jasminechester", "Niger");
insert into JOB_SEEKER_SKILL values (5,"Designer");
insert into JOB_SEEKER_SKILL values (5,"Scientist");
insert into JOB_SEEKER_SKILL values (5,"Agricultural consultant");
insert into JOB_SEEKER_SKILL values (5,"Media planner");
insert into JOB_SEEKER_SKILL values (5,"Tree surgeon");
insert into JOB_SEEKER_SKILL values (5,"Librarian");
insert into EDUCATION values (NULL,"Iste explicabo impedit numquam sequi quas. Ex id nulla magni placeat saepe harum iste molestias. Facilis ipsam aperiam voluptatem dolorum officia iure. Debitis adipisci perspiciatis aliquam quas.","Jensen School","2016-08-16","2016-07-24","High School",5);
insert into EDUCATION values (NULL,"Error dicta ducimus rerum molestias eaque odit sequi nobis. Eum porro optio deserunt eius explicabo. Deserunt esse nam recusandae nam. Rem nihil alias doloribus magni.","Miera Institution","2016-11-22","2016-03-05","Vocational Course",5);
insert into EDUCATION values (NULL,"Quia perferendis nam doloremque deserunt. Nam architecto ab quis id officia blanditiis. Nemo doloribus modi expedita magnam inventore beatae illo.","Martinez Institution","2016-01-30","2016-03-21","Associate's Degree",5);
insert into EDUCATION values (NULL,"Iure harum eum porro. Libero et est quae temporibus blanditiis. Quidem distinctio eaque optio veritatis earum aut aspernatur. Inventore doloremque dignissimos magni pariatur laborum.","Lunsford University","2016-05-07","2016-01-03","Doctorate",5);
insert into WORK_EXPERIENCE values (NULL,"Land/geomatics surveyor","Campbell, Dudley and Taylor","2016-07-30","2016-05-06","Error quia officia molestiae et ducimus earum. Soluta inventore esse hic sit alias. Itaque nisi laboriosam saepe explicabo libero voluptas. Iusto aliquid voluptas dignissimos saepe.",5);
insert into WORK_EXPERIENCE values (NULL,"IT technical support officer","Preston-Stephens","2016-06-05","2016-04-06","Dolorem repudiandae esse nam sit. Numquam corrupti pariatur a animi quo quo ea. Laboriosam atque tempora repellendus asperiores.",5);
insert into WORK_EXPERIENCE values (NULL,"Senior tax professional/tax inspector","Perez-Stanley","2016-08-27","2016-08-04","Deserunt aliquid aliquid ullam a quisquam cupiditate. Esse nihil aliquid veritatis dolorum. Hic nemo perspiciatis et.",5);
insert into WORK_EXPERIENCE values (NULL,"Production assistant, television","Gutierrez Inc","2016-05-28","2016-08-11","Provident vero ut mollitia temporibus porro. Ad fugiat deserunt nihil accusantium facere. Ad sed velit incidunt eligendi tempora.",5);
insert into JOB_SEEKER values (6, "dfuller@martinez.com", "nTP8x8FKFB", "Natus cum corporis voluptate officiis. Ad aperiam iure impedit at sit. Nulla officia ducimus minima delectus voluptatum molestiae porro qui. Ullam repudiandae nesciunt assumenda amet commodi.", CURDATE(), CURDATE(), "2016-02-04", "71365663218", "male", "Scott", "Armstrong", "Johnson", "916 Walker Port Apt. 388", "Lake Jessica", "Bulgaria");
insert into JOB_SEEKER_SKILL values (6,"Editor");
insert into JOB_SEEKER_SKILL values (6,"Agricultural engineer");
insert into JOB_SEEKER_SKILL values (6,"Training and development officer");
insert into JOB_SEEKER_SKILL values (6,"Clinical cytogeneticist");
insert into JOB_SEEKER_SKILL values (6,"Chartered public finance accountant");
insert into JOB_SEEKER_SKILL values (6,"Radiographer");
insert into EDUCATION values (NULL,"Tempora nam porro assumenda neque omnis. Laborum nemo dolore asperiores quasi. Quis reiciendis excepturi placeat.","Flatley Institution","2016-03-22","2016-06-23","Associate's Degree",6);
insert into EDUCATION values (NULL,"Explicabo ut eius laborum excepturi optio quo. Minima et ab laudantium temporibus eum maxime totam porro. Sit aliquam in odio. Harum qui dignissimos numquam incidunt vitae quo quisquam.","Salgado Institution","2016-06-22","2016-04-14","Bachelor's Degree",6);
insert into WORK_EXPERIENCE values (NULL,"Race relations officer","Patterson PLC","2016-11-17","2016-10-14","Doloremque molestias similique nesciunt quos suscipit. Veniam perferendis corporis provident quaerat consequatur.",6);
insert into WORK_EXPERIENCE values (NULL,"Product designer","Turner-Farrell","2016-01-21","2016-03-06","Hic expedita magni quibusdam rem. Suscipit fugiat quam ut amet aperiam.",6);
insert into WORK_EXPERIENCE values (NULL,"Civil engineer, contracting","Martinez-Browning","2016-08-29","2016-07-27","Doloribus dolorem soluta odio repudiandae laborum fugit enim. Assumenda accusantium tempora maiores quia ullam. Explicabo error illum dolores culpa itaque impedit.",6);
insert into JOB_SEEKER values (7, "harperwhitney@davis.com", "0L8lfEcNQm", "Nisi cumque repellendus voluptates exercitationem architecto aspernatur id fuga. Rerum inventore nemo expedita excepturi esse.", CURDATE(), CURDATE(), "2016-03-17", "90084906834", "female", "Marjorie", "Veselka", "Mervis", "474 Keith Square", "Timothyfurt", "Afghanistan");
insert into JOB_SEEKER_SKILL values (7,"Dealer");
insert into JOB_SEEKER_SKILL values (7,"Sports therapist");
insert into JOB_SEEKER_SKILL values (7,"Insurance broker");
insert into JOB_SEEKER_SKILL values (7,"Multimedia specialist");
insert into JOB_SEEKER_SKILL values (7,"Estate agent");
insert into JOB_SEEKER_SKILL values (7,"Audiological scientist");
insert into EDUCATION values (NULL,"Dolorum ab vero beatae provident sit voluptates voluptate. Recusandae quisquam quae aliquam deleniti impedit. Placeat pariatur laudantium dolor in quos non amet. Neque blanditiis sed incidunt.","Roberts School","2016-03-31","2016-11-02","Vocational Course",7);
insert into EDUCATION values (NULL,"Placeat explicabo sint architecto accusantium. Praesentium dignissimos fugiat totam ratione nulla. Enim deleniti nemo sint repellendus. Deserunt atque nesciunt inventore distinctio eos perspiciatis.","Hester University","2016-03-21","2016-01-14","Doctorate",7);
insert into WORK_EXPERIENCE values (NULL,"Surveyor, building","Sanchez, Lin and Mullins","2016-04-18","2016-04-24","Facere blanditiis nihil expedita nihil facere architecto enim. Adipisci ipsam maiores expedita recusandae vero minus. Sint esse iusto laudantium dolor repellendus.",7);
insert into WORK_EXPERIENCE values (NULL,"Outdoor activities/education manager","Lee and Sons","2016-10-23","2016-09-09","Veritatis minus placeat mollitia. Sapiente soluta repellat sunt asperiores beatae quos porro. Fugiat fugiat voluptates aliquam enim aspernatur qui voluptatibus.",7);
insert into WORK_EXPERIENCE values (NULL,"Merchandiser, retail","Jones-White","2016-07-03","2016-03-13","Dignissimos omnis laboriosam ipsum aliquid placeat consectetur. Quo cupiditate totam soluta aut corrupti. At reprehenderit ipsa optio culpa. Fugit sit incidunt commodi alias.",7);
insert into JOB_SEEKER values (8, "elizabeth95@barr-flowers.com", "B4JP2nEAzn", "Blanditiis perspiciatis culpa unde quae dolor. Vero nam voluptatem odio facilis. Ab eum magni eligendi quia. Officiis praesentium recusandae iusto soluta.", CURDATE(), CURDATE(), "2016-05-31", "71150360503", "male", "Brandon", "Jennings", "Patterson", "0475 Dawn Summit", "North Kathryn", "Oman");
insert into JOB_SEEKER_SKILL values (8,"Medical laboratory scientific officer");
insert into JOB_SEEKER_SKILL values (8,"Customer service manager");
insert into JOB_SEEKER_SKILL values (8,"Manufacturing systems engineer");
insert into JOB_SEEKER_SKILL values (8,"Armed forces operational officer");
insert into JOB_SEEKER_SKILL values (8,"Sales professional");
insert into JOB_SEEKER_SKILL values (8,"Secretary");
insert into EDUCATION values (NULL,"Recusandae dolorum debitis doloremque perferendis cumque illo suscipit. Consectetur et quibusdam modi illo sed eius. At totam tempore tenetur quod nulla tenetur nemo.","Bradbury School","2016-01-26","2016-08-21","Doctorate",8);
insert into EDUCATION values (NULL,"Excepturi id modi adipisci distinctio autem. Facilis excepturi veritatis magnam voluptatibus. Ullam aperiam tenetur perferendis cum autem.","Ruiz University","2016-05-26","2016-07-05","Associate's Degree",8);
insert into EDUCATION values (NULL,"Dolores nisi laboriosam natus error alias quasi quisquam. Explicabo suscipit iste molestias expedita natus.","Davy Institution","2016-06-25","2016-01-28","High School",8);
insert into WORK_EXPERIENCE values (NULL,"Surveyor, building control","Conner Ltd","2016-09-16","2016-01-16","Incidunt dicta labore accusantium quidem ex saepe. Numquam numquam voluptas delectus in magnam. Libero quaerat beatae autem.",8);
insert into WORK_EXPERIENCE values (NULL,"Learning mentor","Hernandez, Parker and Bowen","2016-09-04","2016-02-15","Culpa itaque aperiam odit. Provident deserunt animi fugit fugit. Maiores ratione dolores nisi labore.",8);
insert into WORK_EXPERIENCE values (NULL,"Scientist, research (medical)","Jones, Barajas and Baker","2016-08-17","2016-11-12","Deleniti debitis neque quos doloribus id quam. Magni nulla pariatur earum dolore enim.",8);
insert into JOB_SEEKER values (9, "rachael89@gmail.com", "J4OwUC4O", "Distinctio ipsum quia sunt esse. Consectetur aspernatur officiis consectetur. Reprehenderit aliquid facilis voluptates.", CURDATE(), CURDATE(), "2016-04-03", "14416265601", "male", "Jerry", "Barrera", "Houser", "749 Fowler Shoals", "West Katherineview", "Comoros");
insert into JOB_SEEKER_SKILL values (9,"Aid worker");
insert into JOB_SEEKER_SKILL values (9,"Public affairs consultant");
insert into JOB_SEEKER_SKILL values (9,"Glass blower/designer");
insert into JOB_SEEKER_SKILL values (9,"Research officer");
insert into JOB_SEEKER_SKILL values (9,"International aid/development worker");
insert into JOB_SEEKER_SKILL values (9,"Conference centre manager");
insert into EDUCATION values (NULL,"Hic aliquam esse ipsa expedita harum. Laborum nihil distinctio blanditiis vel. Explicabo labore mollitia cumque temporibus.","Swager School","2016-01-28","2016-10-13","Doctorate",9);
insert into WORK_EXPERIENCE values (NULL,"Private music teacher","Dalton, Spears and Nielsen","2016-08-07","2016-10-01","Dolores qui consectetur quo temporibus occaecati sapiente. Atque fuga tempore porro aspernatur. Sequi ullam impedit ex non veritatis expedita.",9);
insert into WORK_EXPERIENCE values (NULL,"Lawyer","Montgomery, Wilson and Willis","2016-08-13","2016-09-16","Optio harum repudiandae officia nulla. Iste quam rem dignissimos molestiae voluptas commodi. Ex molestias doloremque placeat.",9);
insert into WORK_EXPERIENCE values (NULL,"Trade union research officer","Palmer, Mccormick and Flores","2016-11-06","2016-11-03","Dolorem commodi dignissimos ad aliquam minima minus corrupti. Praesentium iusto quidem quae rerum. Libero corrupti voluptate autem aspernatur. Est quisquam magni atque impedit recusandae doloribus.",9);
insert into JOB_SEEKER values (10, "janice47@gmail.com", "eM0a7Tu", "Illo quos nemo veniam odio nemo. Modi quia amet consectetur occaecati tenetur velit.
Ex ut sequi iusto soluta. Quae eaque fugit eaque itaque. Eos saepe consequuntur sapiente maxime fugiat.", CURDATE(), CURDATE(), "2016-06-30", "06710827855", "male", "Reynaldo", "Camel", "Ashburn", "449 Martin Mall Apt. 855", "South Michael", "Saint Barthelemy");
insert into JOB_SEEKER_SKILL values (10,"Administrator");
insert into JOB_SEEKER_SKILL values (10,"Research officer");
insert into JOB_SEEKER_SKILL values (10,"Drilling engineer");
insert into JOB_SEEKER_SKILL values (10,"Advertising account executive");
insert into JOB_SEEKER_SKILL values (10,"Tax inspector");
insert into JOB_SEEKER_SKILL values (10,"Farm manager");
insert into EDUCATION values (NULL,"Dicta commodi nemo esse repudiandae explicabo. Doloremque et doloribus tempore. Inventore dolore quo culpa ipsa harum sint.","Jackson University","2016-10-22","2016-01-14","Master's Degree",10);
insert into WORK_EXPERIENCE values (NULL,"Retail manager","Donaldson, Nelson and Oliver","2016-04-23","2016-06-22","Quos soluta reiciendis sunt error distinctio ipsa quos molestias. Sed rerum exercitationem in fugiat. Maiores tempora aliquid eligendi.",10);
insert into WORK_EXPERIENCE values (NULL,"Doctor, hospital","Velez, Meyer and Smith","2016-01-14","2016-01-07","Ratione praesentium qui blanditiis porro. Error minus similique in a eius. Dignissimos natus quas debitis. Veniam ducimus quidem commodi exercitationem delectus doloribus.",10);
insert into WORK_EXPERIENCE values (NULL,"Air broker","Bailey Inc","2016-08-24","2016-04-02","In officia voluptatem animi culpa unde ipsum molestiae ducimus. Facilis repudiandae officia error. Adipisci quasi consequatur exercitationem officiis molestiae quam enim.",10);
insert into WORK_EXPERIENCE values (NULL,"Transport planner","Vaughn Inc","2016-05-28","2016-04-26","Delectus laboriosam eius corrupti natus quaerat optio. Odio pariatur quia debitis quod recusandae. Iusto similique facere reiciendis accusantium officiis harum quam.",10);
