use jobFinder;

drop table MOCK_DATA; 

create table MOCK_DATA (
	id INT,
	title TEXT,
	description TEXT,
	employment_type VARCHAR(9),
	job_level VARCHAR(26),
	salary VARCHAR(50),
	application_deadline DATE,
	industry VARCHAR(50),
	address VARCHAR(50),
	city VARCHAR(50),
	country VARCHAR(50),
	educational_attainment TEXT,
	skill TEXT,
	work_experience TEXT
);
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (65, 'lorem ipsum', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.', 'Full-time', 'Internship / OJT', '$631062.78', '7/12/2016', 'Services', '10317 5th Court', 'Sayang Lauq', 'Indonesia', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 'augue', 'eget vulputate');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (9, 'leo pellentesque', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'Part-time', 'Mid-Senior Level / Manager', '$630610.59', '3/23/2016', 'Product Management', '8267 Schiller Court', 'Jiancha', 'China', 'Praesent lectus.', 'ante vivamus tortor', 'vitae ipsum');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (28, 'sit', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', 'Full-time', 'Associate / Supervisor', '$792609.95', '10/13/2016', 'Research and Development', '0214 Trailsway Court', 'Milotice', 'Czech Republic', 'Morbi a ipsum.', 'varius', 'mauris non');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (48, 'sapien', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', 'Full-time', 'Fresh Grad / Entry Level', '$870054.39', '12/2/2015', 'Sales', '62 Canary Center', 'Ulundi', 'South Africa', 'Proin risus. Praesent lectus.', 'morbi odio odio', 'blandit');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (29, 'auctor', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Part-time', 'Director / Executive', '$63270.30', '11/4/2016', 'Marketing', '82 Kensington Street', 'Kostrovo', 'Russia', 'Maecenas ut massa quis augue luctus tincidunt.', 'nulla neque libero', 'ligula pellentesque');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (63, 'in felis', 'Nullam sit amet turpis elementum ligula vehicula consequat.', 'Part-time', 'Director / Executive', '$462165.79', '4/29/2016', 'Sales', '62 Forest Dale Court', 'Kozova', 'Ukraine', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 'maecenas tristique est', 'imperdiet');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (5, 'nulla', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 'Full-time', 'Internship / OJT', '$956088.62', '12/17/2015', 'Marketing', '847 Parkside Street', 'Zhaojia', 'China', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 'consectetuer', 'cursus id turpis');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (43, 'luctus et', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 'Part-time', 'Internship / OJT', '$187938.66', '9/18/2016', 'Engineering', '7 Bultman Circle', 'Shuangyang', 'China', 'Aliquam erat volutpat. In congue. Etiam justo.', 'nulla', 'odio condimentum id');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (45, 'habitasse platea', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 'Full-time', 'Director / Executive', '$12519.46', '8/22/2016', 'Sales', '46155 Raven Circle', 'Podhum', 'Bosnia and Herzegovina', 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.', 'et magnis dis', 'nullam sit');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (89, 'justo nec', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', 'Part-time', 'Internship / OJT', '$860595.25', '5/3/2016', 'Training', '08 Lyons Court', 'Tajur', 'Indonesia', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 'faucibus orci', 'platea dictumst');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (2, 'volutpat', 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 'Part-time', 'Associate / Supervisor', '$377405.11', '3/21/2016', 'Research and Development', '45 Cherokee Plaza', 'Eystur', 'Faroe Islands', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'volutpat erat', 'mi');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (32, 'pellentesque', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 'Full-time', 'Fresh Grad / Entry Level', '$253524.70', '1/13/2016', 'Services', '2 Moose Circle', 'Kristinehamn', 'Sweden', 'In quis justo. Maecenas rhoncus aliquam lacus.', 'at', 'felis fusce posuere');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (75, 'sagittis sapien', 'Sed accumsan felis.', 'Part-time', 'Mid-Senior Level / Manager', '$569317.09', '2/16/2016', 'Product Management', '6966 Anzinger Park', 'Nema', 'Russia', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 'rhoncus aliquet pulvinar', 'ut nunc');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (74, 'ante nulla', 'In hac habitasse platea dictumst.', 'Full-time', 'Associate / Supervisor', '$200544.19', '8/29/2016', 'Training', '97494 Golf Drive', 'Shuanglong', 'China', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', 'nisi volutpat eleifend', 'eu massa donec');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (55, 'enim sit', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', 'Full-time', 'Mid-Senior Level / Manager', '$654707.01', '12/4/2015', 'Training', '63968 Cherokee Court', 'Besteiros', 'Portugal', 'Nam tristique tortor eu pede.', 'eget orci', 'at dolor quis');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (11, 'primis in', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', 'Part-time', 'Associate / Supervisor', '$538962.59', '5/24/2016', 'Research and Development', '215 Rutledge Court', 'Ambulong', 'Philippines', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 'ut erat curabitur', 'amet');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (13, 'ut odio', 'Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 'Part-time', 'Mid-Senior Level / Manager', '$725228.22', '6/21/2016', 'Marketing', '950 Granby Trail', 'Shihuang', 'China', 'Quisque ut erat.', 'donec', 'at');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (92, 'id consequat', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Part-time', 'Director / Executive', '$756799.35', '10/8/2016', 'Support', '2 Union Center', 'Malin', 'China', 'Nullam molestie nibh in lectus.', 'pretium quis lectus', 'ridiculus mus');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (62, 'pulvinar', 'Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.', 'Full-time', 'Director / Executive', '$75404.47', '5/13/2016', 'Engineering', '2 5th Alley', 'Danville', 'Canada', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'ipsum', 'in');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (94, 'neque', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 'Full-time', 'Internship / OJT', '$416872.00', '12/30/2015', 'Support', '00320 Luster Terrace', 'Vykhino-Zhulebino', 'Russia', 'Donec semper sapien a libero.', 'rutrum neque', 'sapien dignissim vestibulum');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (20, 'tincidunt eget', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'Full-time', 'Associate / Supervisor', '$833642.86', '12/29/2015', 'Legal', '3051 Longview Pass', 'Bulusari', 'Indonesia', 'Donec posuere metus vitae ipsum. Aliquam non mauris.', 'laoreet', 'congue eget semper');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (75, 'erat', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.', 'Full-time', 'Internship / OJT', '$222866.78', '7/10/2016', 'Support', '8 Florence Terrace', 'Shinan', 'China', 'Proin interdum mauris non ligula pellentesque ultrices.', 'ipsum primis', 'nulla');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (49, 'maecenas', 'Aenean lectus.', 'Full-time', 'Director / Executive', '$330251.26', '5/19/2016', 'Research and Development', '10 Golden Leaf Park', 'Yambrasbamba', 'Peru', 'Etiam justo. Etiam pretium iaculis justo.', 'rutrum neque aenean', 'dictumst maecenas ut');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (72, 'nec sem', 'Morbi ut odio.', 'Full-time', 'Fresh Grad / Entry Level', '$361471.48', '9/9/2016', 'Business Development', '4217 Pawling Pass', 'Changhe', 'China', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', 'odio in hac', 'pellentesque');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (13, 'non interdum', 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'Part-time', 'Associate / Supervisor', '$798021.39', '7/22/2016', 'Human Resources', '03492 Armistice Plaza', 'Columbus', 'United States', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 'vulputate nonummy', 'ipsum');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (43, 'velit', 'Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.', 'Part-time', 'Director / Executive', '$394087.00', '1/15/2016', 'Human Resources', '2443 Roth Drive', 'Victoriaville', 'Canada', 'Donec dapibus. Duis at velit eu est congue elementum.', 'turpis donec posuere', 'pede malesuada');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (33, 'velit', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 'Part-time', 'Internship / OJT', '$287074.17', '5/24/2016', 'Legal', '1903 Golden Leaf Avenue', 'Sayán', 'Peru', 'Etiam vel augue.', 'a', 'penatibus et magnis');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (6, 'interdum', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 'Part-time', 'Associate / Supervisor', '$113538.56', '6/19/2016', 'Marketing', '1852 Bonner Street', 'Belverde', 'Portugal', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.', 'in lacus', 'elementum ligula');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (36, 'habitasse', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Full-time', 'Internship / OJT', '$205861.22', '12/16/2015', 'Engineering', '6 Express Hill', 'Goiana', 'Brazil', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 'congue etiam justo', 'mauris non');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (42, 'dui maecenas', 'Maecenas pulvinar lobortis est.', 'Full-time', 'Associate / Supervisor', '$373707.23', '6/12/2016', 'Product Management', '741 Melvin Alley', 'Tulsa', 'United States', 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'lectus', 'sollicitudin vitae');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (76, 'tempor', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.', 'Part-time', 'Associate / Supervisor', '$945796.02', '7/24/2016', 'Marketing', '91 Dexter Court', 'Jincheng', 'China', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 'non velit', 'placerat praesent');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (89, 'ultrices posuere', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'Full-time', 'Fresh Grad / Entry Level', '$36723.22', '1/14/2016', 'Research and Development', '142 Farwell Circle', 'Krasnyy Oktyabr’', 'Russia', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 'vel est donec', 'dis parturient montes');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (58, 'iaculis diam', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Part-time', 'Director / Executive', '$159415.35', '8/26/2016', 'Research and Development', '41 Reinke Junction', 'Drummondville', 'Canada', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'sagittis sapien', 'in');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (39, 'felis', 'Vestibulum rutrum rutrum neque.', 'Full-time', 'Internship / OJT', '$182381.08', '10/6/2016', 'Human Resources', '366 Sutherland Trail', 'Fort Lauderdale', 'United States', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 'eu', 'dolor');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (98, 'risus', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 'Part-time', 'Mid-Senior Level / Manager', '$469510.23', '3/15/2016', 'Research and Development', '924 Warner Court', 'Tajan', 'Indonesia', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'consectetuer adipiscing elit', 'amet');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (59, 'ultrices', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 'Part-time', 'Mid-Senior Level / Manager', '$352736.28', '6/2/2016', 'Training', '02 Sunfield Road', 'Atsipópoulon', 'Greece', 'Cras non velit nec nisi vulputate nonummy.', 'morbi', 'at');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (69, 'phasellus', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', 'Part-time', 'Internship / OJT', '$946315.01', '10/6/2016', 'Support', '4 Moulton Pass', 'Zhongguanyi', 'China', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 'suspendisse potenti in', 'eu felis');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (4, 'metus', 'In hac habitasse platea dictumst.', 'Full-time', 'Fresh Grad / Entry Level', '$757435.54', '2/21/2016', 'Research and Development', '7886 Armistice Park', 'Stylída', 'Greece', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 'luctus', 'volutpat in');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (2, 'nisl', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 'Full-time', 'Associate / Supervisor', '$422744.37', '5/22/2016', 'Training', '64588 Maple Wood Way', 'Fort-de-France', 'Martinique', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'suscipit', 'vestibulum aliquet');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (34, 'sapien', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', 'Full-time', 'Fresh Grad / Entry Level', '$825566.13', '10/24/2016', 'Research and Development', '052 Grim Park', 'Tetyushi', 'Russia', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'odio', 'quis libero');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (28, 'at', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'Full-time', 'Fresh Grad / Entry Level', '$853981.52', '3/5/2016', 'Engineering', '87955 Pennsylvania Junction', 'Santo António das Areias', 'Portugal', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'ut', 'lobortis ligula');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (50, 'est', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 'Full-time', 'Associate / Supervisor', '$740071.38', '7/4/2016', 'Services', '3 Sloan Way', 'Shouchang', 'China', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'tincidunt eu', 'diam');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (73, 'vestibulum', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Full-time', 'Associate / Supervisor', '$788560.27', '6/1/2016', 'Engineering', '29 3rd Street', 'Vera', 'Argentina', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'luctus', 'at turpis');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (22, 'morbi', 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 'Full-time', 'Associate / Supervisor', '$858616.76', '1/26/2016', 'Research and Development', '41930 Lawn Avenue', 'La Agustina', 'Dominican Republic', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 'id', 'sed vestibulum');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (11, 'ut at', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', 'Full-time', 'Fresh Grad / Entry Level', '$373504.61', '2/7/2016', 'Support', '9 Pankratz Park', 'Foz Sousa', 'Portugal', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'porta', 'consequat ut nulla');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (20, 'tristique tortor', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 'Full-time', 'Mid-Senior Level / Manager', '$641568.41', '4/12/2016', 'Business Development', '613 Continental Center', 'Vyšší Brod', 'Czech Republic', 'Nulla mollis molestie lorem. Quisque ut erat.', 'pretium nisl ut', 'imperdiet et');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (7, 'amet nunc', 'Nullam varius.', 'Full-time', 'Director / Executive', '$789642.48', '6/8/2016', 'Research and Development', '270 Golf View Court', 'Ogaminan', 'Nigeria', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', 'ut suscipit a', 'nulla');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (36, 'semper', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'Full-time', 'Associate / Supervisor', '$42044.92', '12/5/2015', 'Training', '3563 Waywood Street', 'Columbus', 'United States', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'rutrum nulla tellus', 'rutrum nulla tellus');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (65, 'vestibulum', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', 'Part-time', 'Director / Executive', '$202125.85', '5/23/2016', 'Engineering', '447 Lakewood Gardens Drive', 'Port Said', 'Egypt', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 'ante vestibulum', 'luctus');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (65, 'in', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.', 'Full-time', 'Internship / OJT', '$794682.36', '2/15/2016', 'Services', '54600 Eggendart Place', 'Dalun', 'China', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', 'morbi ut', 'aliquet');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (91, 'neque aenean', 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Part-time', 'Fresh Grad / Entry Level', '$442494.62', '4/24/2016', 'Sales', '97527 Toban Place', 'Leskovac', 'Serbia', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.', 'dolor vel est', 'amet');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (3, 'vestibulum ante', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 'Part-time', 'Mid-Senior Level / Manager', '$462402.33', '10/29/2016', 'Business Development', '6 Thierer Terrace', 'Szczytno', 'Poland', 'Phasellus id sapien in sapien iaculis congue.', 'velit eu est', 'nunc proin');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (55, 'nec sem', 'Morbi quis tortor id nulla ultrices aliquet.', 'Part-time', 'Director / Executive', '$967909.43', '5/16/2016', 'Product Management', '01 Thackeray Point', 'Novi Travnik', 'Bosnia and Herzegovina', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'maecenas pulvinar', 'morbi a');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (62, 'justo', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 'Full-time', 'Fresh Grad / Entry Level', '$437993.82', '12/10/2015', 'Sales', '3295 Sachs Plaza', 'Hor', 'China', 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', 'ultrices posuere', 'ligula in');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (38, 'pretium quis', 'Integer tincidunt ante vel ipsum.', 'Full-time', 'Director / Executive', '$972699.84', '1/16/2016', 'Marketing', '6 Spaight Lane', 'Göteborg', 'Sweden', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 'amet eleifend pede', 'phasellus');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (76, 'sed magna', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Part-time', 'Fresh Grad / Entry Level', '$743295.03', '5/8/2016', 'Research and Development', '3 Buhler Park', 'Куклиш', 'Macedonia', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'luctus tincidunt', 'ante vestibulum ante');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (58, 'nullam molestie', 'Pellentesque viverra pede ac diam.', 'Part-time', 'Internship / OJT', '$976783.53', '3/21/2016', 'Training', '38 Washington Junction', 'Korczyna', 'Poland', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'lectus pellentesque', 'eu massa donec');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (69, 'maecenas tincidunt', 'Morbi vel lectus in quam fringilla rhoncus.', 'Full-time', 'Internship / OJT', '$259217.54', '7/3/2016', 'Legal', '2 Red Cloud Plaza', 'Belos Ares', 'Portugal', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 'mi', 'justo sollicitudin ut');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (7, 'mi integer', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Part-time', 'Associate / Supervisor', '$302371.28', '2/10/2016', 'Business Development', '2572 Portage Road', 'Morrison', 'Argentina', 'Sed vel enim sit amet nunc viverra dapibus.', 'molestie hendrerit', 'mauris');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (87, 'tellus nulla', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'Part-time', 'Fresh Grad / Entry Level', '$593123.23', '11/20/2015', 'Accounting', '4943 Bobwhite Drive', 'Lalig', 'Philippines', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 'iaculis', 'praesent lectus');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (29, 'libero ut', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 'Full-time', 'Director / Executive', '$774764.74', '10/15/2016', 'Sales', '61577 Clyde Gallagher Park', 'Kyprínos', 'Greece', 'Nulla mollis molestie lorem. Quisque ut erat.', 'libero rutrum', 'rutrum rutrum neque');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (67, 'non quam', 'Nullam porttitor lacus at turpis.', 'Full-time', 'Fresh Grad / Entry Level', '$856291.55', '9/11/2016', 'Support', '88045 Mesta Terrace', 'Cienfuegos', 'Cuba', 'Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 'nulla ut', 'vestibulum');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (90, 'orci', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Part-time', 'Internship / OJT', '$89967.93', '10/19/2016', 'Training', '0534 Glendale Park', 'Washington', 'United States', 'Mauris ullamcorper purus sit amet nulla.', 'amet nulla quisque', 'ligula');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (37, 'nec', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.', 'Full-time', 'Fresh Grad / Entry Level', '$111180.70', '10/14/2016', 'Marketing', '6 Lotheville Pass', 'Osilnica', 'Slovenia', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'felis sed', 'sapien');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (10, 'at', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'Full-time', 'Director / Executive', '$629954.84', '7/9/2016', 'Support', '63374 Talmadge Terrace', 'Shuangyang', 'China', 'Mauris ullamcorper purus sit amet nulla.', 'ac', 'eu interdum eu');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (92, 'elit', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Full-time', 'Fresh Grad / Entry Level', '$844849.53', '4/5/2016', 'Research and Development', '6193 Donald Court', 'Milići', 'Bosnia and Herzegovina', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', 'viverra eget', 'morbi');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (58, 'rhoncus dui', 'Fusce posuere felis sed lacus.', 'Full-time', 'Mid-Senior Level / Manager', '$434289.38', '9/24/2016', 'Support', '1 Talmadge Street', 'Dulangan', 'Philippines', 'Ut tellus. Nulla ut erat id mauris vulputate elementum.', 'nec', 'eu');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (41, 'urna ut', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Part-time', 'Associate / Supervisor', '$872574.08', '10/10/2016', 'Support', '4 Michigan Avenue', 'Szczytno', 'Poland', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'cras pellentesque volutpat', 'quam');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (68, 'ultrices', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Part-time', 'Internship / OJT', '$493315.37', '10/4/2016', 'Engineering', '7828 Sloan Junction', 'Cotton Ground', 'Saint Kitts and Nevis', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 'massa volutpat', 'ac neque duis');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (37, 'luctus et', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', 'Full-time', 'Mid-Senior Level / Manager', '$904881.23', '3/5/2016', 'Engineering', '5 Carberry Plaza', 'Asia', 'Peru', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', 'integer a', 'in faucibus orci');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (78, 'vitae', 'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'Part-time', 'Director / Executive', '$839475.78', '8/6/2016', 'Support', '31 Bluestem Court', 'Kut Bak', 'Thailand', 'Etiam faucibus cursus urna.', 'magna', 'pede venenatis');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (6, 'consequat morbi', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Full-time', 'Director / Executive', '$233159.12', '12/7/2015', 'Product Management', '314 Sachs Terrace', 'Ploso Wetan', 'Indonesia', 'In quis justo.', 'sit amet diam', 'eget orci');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (42, 'viverra', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 'Part-time', 'Internship / OJT', '$335313.77', '4/26/2016', 'Marketing', '159 Judy Parkway', 'Trieste', 'Italy', 'Pellentesque ultrices mattis odio. Donec vitae nisi.', 'eu orci', 'varius');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (57, 'nulla', 'Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', 'Full-time', 'Internship / OJT', '$121032.08', '6/14/2016', 'Sales', '4316 Moulton Lane', 'Saku', 'Japan', 'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.', 'pede morbi porttitor', 'non velit');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (41, 'aliquet massa', 'Proin risus. Praesent lectus.', 'Full-time', 'Fresh Grad / Entry Level', '$491146.05', '3/30/2016', 'Marketing', '4603 Longview Alley', 'Lajedo', 'Brazil', 'Etiam pretium iaculis justo.', 'elementum', 'adipiscing elit');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (63, 'sapien cursus', 'Nulla facilisi.', 'Full-time', 'Director / Executive', '$136095.05', '7/7/2016', 'Support', '933 Loftsgordon Terrace', 'Paris 15', 'France', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'id', 'ridiculus');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (24, 'praesent', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 'Full-time', 'Fresh Grad / Entry Level', '$35921.65', '6/5/2016', 'Support', '390 Delladonna Court', 'Kurgan', 'Russia', 'Maecenas ut massa quis augue luctus tincidunt.', 'ultrices aliquet', 'maecenas tristique est');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (35, 'faucibus', 'Integer a nibh.', 'Full-time', 'Associate / Supervisor', '$742875.04', '7/4/2016', 'Legal', '421 Thompson Center', 'Bergem', 'Luxembourg', 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 'faucibus orci luctus', 'at');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (88, 'posuere', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Full-time', 'Associate / Supervisor', '$62317.32', '6/17/2016', 'Sales', '82 Golf Course Road', 'Kouvola', 'Finland', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 'ipsum', 'risus dapibus augue');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (66, 'nibh in', 'Aliquam quis turpis eget elit sodales scelerisque.', 'Full-time', 'Mid-Senior Level / Manager', '$484959.41', '3/9/2016', 'Training', '2056 Killdeer Circle', 'Gołkowice', 'Poland', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', 'proin interdum mauris', 'nulla');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (27, 'orci', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', 'Part-time', 'Internship / OJT', '$645361.51', '7/1/2016', 'Business Development', '63244 Springs Road', 'Yangpu', 'China', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 'malesuada in', 'auctor gravida');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (14, 'blandit', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 'Part-time', 'Fresh Grad / Entry Level', '$926969.89', '3/12/2016', 'Business Development', '3 Bultman Alley', 'Sirghāyā', 'Syria', 'Duis mattis egestas metus. Aenean fermentum.', 'nunc viverra', 'eros');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (18, 'vel', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Full-time', 'Fresh Grad / Entry Level', '$765195.04', '3/28/2016', 'Human Resources', '3430 Lakeland Center', 'Moratuwa', 'Sri Lanka', 'Maecenas ut massa quis augue luctus tincidunt.', 'sed tincidunt', 'vel');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (44, 'posuere', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.', 'Part-time', 'Mid-Senior Level / Manager', '$904753.00', '11/19/2015', 'Services', '53 Melody Drive', 'Huanglin', 'China', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'pellentesque', 'primis in');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (92, 'nulla', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', 'Part-time', 'Associate / Supervisor', '$506078.12', '7/30/2016', 'Sales', '21 Novick Alley', 'Miches', 'Dominican Republic', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', 'luctus cum', 'justo maecenas rhoncus');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (72, 'sapien', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.', 'Part-time', 'Internship / OJT', '$815478.66', '8/31/2016', 'Business Development', '05651 Mosinee Trail', 'Krugersdorp', 'South Africa', 'Integer ac leo. Pellentesque ultrices mattis odio.', 'nec', 'integer');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (88, 'porttitor pede', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.', 'Full-time', 'Internship / OJT', '$613351.81', '2/29/2016', 'Business Development', '696 Bartillon Alley', 'Taourirt', 'Morocco', 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 'nulla', 'urna pretium nisl');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (24, 'velit donec', 'In eleifend quam a odio. In hac habitasse platea dictumst.', 'Part-time', 'Mid-Senior Level / Manager', '$599044.45', '9/12/2016', 'Product Management', '0 Elmside Point', 'Cartagena', 'Colombia', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 'consectetuer', 'ultrices posuere cubilia');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (37, 'sagittis nam', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 'Full-time', 'Mid-Senior Level / Manager', '$930728.43', '11/7/2016', 'Training', '57 Steensland Way', 'Dafeng', 'China', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.', 'orci', 'ut massa quis');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (90, 'ligula', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 'Part-time', 'Fresh Grad / Entry Level', '$726855.12', '9/16/2016', 'Marketing', '69897 Sage Road', 'Bo Kluea', 'Thailand', 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 'et magnis dis', 'arcu');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (23, 'massa', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 'Full-time', 'Associate / Supervisor', '$785064.54', '2/22/2016', 'Sales', '534 Rusk Drive', 'Embajador Martini', 'Argentina', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'primis in', 'id luctus');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (82, 'eget', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 'Part-time', 'Associate / Supervisor', '$117377.45', '12/5/2015', 'Legal', '2868 Elgar Drive', 'Várzea da Palma', 'Brazil', 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 'nulla', 'condimentum');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (94, 'a', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', 'Part-time', 'Internship / OJT', '$488936.19', '8/15/2016', 'Support', '757 Prentice Lane', 'Shuitai', 'China', 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 'erat curabitur', 'eget tincidunt');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (80, 'in', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 'Full-time', 'Director / Executive', '$851096.14', '7/12/2016', 'Accounting', '7 Jenifer Parkway', 'Alhambra', 'United States', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'luctus ultricies eu', 'montes nascetur ridiculus');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (1, 'in', 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Part-time', 'Mid-Senior Level / Manager', '$709463.58', '12/20/2015', 'Human Resources', '91 Park Meadow Plaza', 'Trollhättan', 'Sweden', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'vestibulum ante', 'morbi porttitor');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (35, 'ultrices', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', 'Full-time', 'Director / Executive', '$768536.51', '1/22/2016', 'Training', '9188 Sundown Court', 'Manyava', 'Ukraine', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 'velit id', 'eu est');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (65, 'nisl aenean', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'Full-time', 'Mid-Senior Level / Manager', '$448558.07', '1/25/2016', 'Accounting', '42006 Boyd Point', 'Piggotts', 'Antigua and Barbuda', 'Ut tellus.', 'nullam molestie nibh', 'etiam');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (35, 'at ipsum', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Full-time', 'Associate / Supervisor', '$449107.84', '2/17/2016', 'Training', '18 Nelson Place', 'Balayong', 'Philippines', 'In quis justo.', 'mattis', 'eros');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (64, 'ipsum', 'Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 'Part-time', 'Associate / Supervisor', '$824851.40', '1/29/2016', 'Accounting', '890 Thierer Center', 'Ciherang', 'Indonesia', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', 'vel', 'ante vivamus');
insert into MOCK_DATA (id, title, description, employment_type, job_level, salary, application_deadline, industry, address, city, country, educational_attainment, skill, work_experience) values (62, 'molestie', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', 'Full-time', 'Internship / OJT', '$449259.31', '11/7/2016', 'Research and Development', '506 Lakewood Gardens Avenue', 'Chilecito', 'Argentina', 'Nullam varius.', 'condimentum neque', 'in hac habitasse');
